#!/usr/bin/env python3
#
############################# INTELLECTUAL PROPERTY RIGHTS #############################
##                                                                                    ##
##                           Copyright (c) 2024 Terminus LLC                          ##
##                                All Rights Reserved.                                ##
##                                                                                    ##
##          Use of this source code is governed by LICENSE in the repo root.          ##
##                                                                                    ##
############################# INTELLECTUAL PROPERTY RIGHTS #############################
#
#    File:    tmns-profile-info.py
#    Author:  Marvin Smith
#    Date:    11/19/2025
#
#    Purpose:  Inspect and generate Terminus workspace profile documents.

#  Python Standard Libraries
import argparse
import configparser
import datetime
import os
import sys

#  Terminus Libraries
from tmns.default_profiles import default_profile
from tmns.profile import Profile, Repo


DEFAULT_PROFILE_PATH = "tmns-profile.cfg"


def parse_command_line() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description="Inspect or generate a Terminus workspace profile document.",
    )

    parser.add_argument(
        "-p",
        "--profile-path",
        dest="profile_path",
        default=DEFAULT_PROFILE_PATH,
        help="Path to the profile configuration file (default: tmns-profile.cfg)",
    )

    parser.add_argument(
        "--create-default",
        dest="create_default",
        action="store_true",
        default=False,
        help="Create a default profile document at the given path and exit.",
    )

    return parser.parse_args()


def profile_to_config(profile: Profile) -> configparser.ConfigParser:

    cfg = configparser.ConfigParser()

    # Global profile metadata
    cfg["profile"] = {
        "project_name": profile.project_name,
    }

    # One section per repo, with all fields listed
    for repo in profile.repos:
        section = repo.repo_name
        cfg[section] = {
            "repo_name": repo.repo_name,
            "build": str(repo.build).lower(),
            "repo_url": repo.repo_url,
            "branch_name": repo.branch_name,
            "tags": ",".join(repo.tags),
        }

    return cfg


def write_profile_config(profile: Profile, profile_path: str) -> None:

    # Manually write a commented, configparser-compatible profile file.

    with open(profile_path, "w", encoding="utf-8") as output:

        current_date = datetime.date.today().strftime( "%Y/%m/%d %H:%M:%S" )

        # File-level header (mirrors standard Terminus Python headers)
        output.write("############################# INTELLECTUAL PROPERTY RIGHTS #############################\n")
        output.write("##                                                                                    ##\n")
        output.write("##                           Copyright (c) 2024 Terminus LLC                          ##\n")
        output.write("##                                All Rights Reserved.                                ##\n")
        output.write("##                                                                                    ##\n")
        output.write("##          Use of this source code is governed by LICENSE in the repo root.          ##\n")
        output.write("##                                                                                    ##\n")
        output.write("############################# INTELLECTUAL PROPERTY RIGHTS #############################\n")
        output.write("#\n")
        output.write(f"#    File:    {os.path.basename(profile_path)}\n")
        output.write( "#    Author:  Marvin Smith\n")
        output.write(f"#    Date:    {current_date}\n")
        output.write("#\n")
        output.write("#    Purpose:  Terminus workspace profile configuration\n")
        output.write("#\n")
        output.write("#  Generated by tmns-profile-info.py --create-default\n")
        output.write("#  Edit this file to customize which repos are included in your workspace.\n")
        output.write("#  Each section below describes a single repository.\n\n")

        # Global profile section
        output.write("[profile]\n")
        output.write(f"project_name = {profile.project_name}\n\n")

        # One section per repo
        for repo in profile.repos:

            build_value = "true" if repo.build else "false"

            output.write(f"# Repo: {repo.repo_name}\n")
            output.write(f"[{repo.repo_name}]\n")
            output.write(f"repo_name = {repo.repo_name}\n")
            output.write(f"build = {build_value}\n")
            output.write(f"repo_url = {repo.repo_url}\n")
            output.write(f"branch_name = {repo.branch_name}\n")
            output.write(f"tags = {','.join(repo.tags)}\n\n")


def load_profile_from_config(profile_path: str) -> Profile | None:

    if os.path.exists(profile_path) is False:
        print(f"Profile file not found: {profile_path}")
        return None

    cfg = configparser.ConfigParser()
    cfg.read(profile_path)

    project_name = cfg.get("profile", "project_name", fallback="Unknown Profile")

    repos: list[Repo] = []
    for section in cfg.sections():
        if section == "profile":
            continue

        repo_name = cfg.get(section, "repo_name", fallback=section)
        build = cfg.getboolean(section, "build", fallback=True)
        repo_url = cfg.get(section, "repo_url", fallback="")
        branch_name = cfg.get(section, "branch_name", fallback="main")
        tags_raw = cfg.get(section, "tags", fallback="")
        tags = [tag.strip() for tag in tags_raw.split(",") if tag.strip()]

        repos.append(
            Repo(
                repo_name=repo_name,
                build=build,
                repo_url=repo_url,
                branch_name=branch_name,
                tags=tags,
            )
        )

    return Profile(
        project_name=project_name,
        repos=repos,
    )


def print_profile_info(profile: Profile) -> None:

    print(f"Project Name: {profile.project_name}")
    print(f"Repo Count : {len(profile.repos)}")
    print()

    for repo in profile.repos:
        print(f"[ {repo.repo_name} ]")
        print(f"  build       : {repo.build}")
        print(f"  repo_url    : {repo.repo_url}")
        print(f"  branch_name : {repo.branch_name}")
        print(f"  tags        : {', '.join(repo.tags)}")
        print()


def main() -> int:

    cmd_args = parse_command_line()

    # Create a default profile document
    if cmd_args.create_default:
        profile = default_profile()
        write_profile_config(profile, cmd_args.profile_path)
        print(f"Wrote default profile to: {cmd_args.profile_path}")
        return 0

    # Default behavior: read and print information about an existing profile
    profile = load_profile_from_config(cmd_args.profile_path)
    if profile is None:
        return 1

    print_profile_info(profile)
    return 0


if __name__ == "__main__":
    sys.exit(main())

